.PHONY: clean All

All:
	@echo "----------Building project:[ fu - Debug ]----------"
	@"$(MAKE)" -f  "fu.mk" && "$(MAKE)" -f  "fu.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ fu - Debug ]----------"
	@"$(MAKE)" -f  "fu.mk" clean
